# Generated by Django 5.1.3 on 2024-11-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsreport',
            name='branch',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
