# Generated by Django 5.1.3 on 2024-11-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_productsreport_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsreport',
            name='resolved',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
