# Generated by Django 5.1.3 on 2024-11-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_productsreport_category_sap_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsreport',
            name='fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
