# Generated by Django 5.1.3 on 2024-11-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_productsreport_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsreport',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
