# Generated by Django 5.1.3 on 2024-11-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_productsreport_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsreport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
