# Generated by Django 5.1.3 on 2024-11-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_productsreport_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsreport',
            name='category_sap_code_name',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsreport',
            name='sap_code_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
