# Generated by Django 5.1.3 on 2024-11-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_productsreport_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsreport',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
