# Generated by Django 5.1.3 on 2024-11-14 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_count_productsreport_stock_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerreason',
            name='fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productsreport',
            name='manager_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_reports', to='main.managerreason'),
        ),
    ]
