# Generated by Django 5.1.3 on 2024-11-19 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_branch_telegramuserstatus_telegramuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.branch'),
        ),
    ]
