# Generated by Django 5.1.3 on 2024-11-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_userreview_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerreason',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
