# Generated by Django 5.1.3 on 2024-11-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_managerreason_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='user_bonus',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
