# Generated by Django 5.1.3 on 2024-11-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_telegramuser_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsreport',
            name='is_kilogram',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='productsreport',
            name='order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productsreport',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
