# Generated by Django 5.1.3 on 2024-12-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_telegramuser_tabel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('month_year', models.CharField(max_length=50)),
                ('out_of_stock', models.JSONField()),
                ('product_quality', models.JSONField()),
                ('expire_date', models.JSONField()),
                ('total', models.JSONField()),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
