# Generated by Django 5.1.3 on 2025-01-29 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_userreview_rate_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewsCategoryAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.reviewscategory')),
            ],
        ),
    ]
