# Generated by Django 5.1.3 on 2025-01-29 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_reviewscategoryanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='category_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.reviewscategoryanswer'),
        ),
    ]
