# Generated by Django 5.1.3 on 2025-02-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_userreview_category_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='category_answer_comment',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userreview',
            name='category_comment',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
