# Generated by Django 5.1.3 on 2025-02-05 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_userreview_category_answer_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreview',
            old_name='rate_date',
            new_name='order_date',
        ),
    ]
